### PR TITLE
add missing check if io-pack is corrupted or non existing

### LINKED ISSUE #1407: Upload error: missing check
javascript v 5.2.8 after the iobroker upload javascript

/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:485
            (isAdmin || cfg.common.onlyWWW) && console.log(`INFO: Directory "${dir || ('for ' + adapter + (isAdmin ? '.admin' : ''))}" was not found! Nothing was uploaded or deleted.`);
                            ^

TypeError: Cannot read property 'common' of undefined
    at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:485:29)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:247:34
    at Upload.upgradeAdapterObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:750:13)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:246:30
    at upload (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:370:51)
    at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:419:38)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

### PR DESCRIPTION
**Pull request by foxriver76**
- fixes #1407

### CODE REVIEW

**Comment by Apollon77** [comment]
I was mainly asking myself if we should not better make sure to handle the root cause ... because a non existing io-package is a bigger deal then "Just that followup" error ... 
Does it make sense at all to continue if io-package could not be read?

**Comment by foxriver76** [comment]
basically in the following code there were such checks, and it also only reads if io-pack is there. so yes you could just else lgo error exit if this is what you meant

**Comment by Apollon77** [comment]
@GermanBluefox @AlCalzone opinions?

@GermanBluefox Are there valid cases for an upload when io-package is not there?

**Comment by AlCalzone** [comment]
Well, we do these extensive checks in the following sections - so it makes sense to check here too.

On the other hand you could ask why the upload can proceed at all without an io-package.json.
I think it shouldn't.

**Review by AlCalzone — APPROVED** [review]

**Comment by GermanBluefox** [comment]
> Well, we do these extensive checks in the following sections - so it makes sense to check here too.
> 
> On the other hand you could ask why the upload can proceed at all without an io-package.json.
> I think it shouldn't.

I think too: there is no use-case without io-package.json

**Comment by Apollon77** [comment]
I merge here and have created https://github.com/ioBroker/ioBroker.js-controller/issues/1432 as followup

**Pull request merged**
