### PR TITLE
Small fixes for 3.2

### PR DESCRIPTION
**Pull request by AlCalzone**
Seems this parameter was dropped during refactoring :)

### CODE REVIEW

**Review by foxriver76 — APPROVED** [review]
lgtm

**Comment by AlCalzone** [comment]
What is going on with that one Windows build on every PR?

**Comment by foxriver76** [comment]
Here it’s 14 in my pr it’s node 12. Don’t now why it is that unstable

**Comment by foxriver76** [comment]
Also different Tests fail but both Timeouts

**Pull request merged**
