### PR TITLE
 we warn if object not exists when setting a state via adapter.set*State*

### PR DESCRIPTION
**Pull request by foxriver76**
- implements the idea of #230

### CODE REVIEW

**Comment by GermanBluefox** [comment]
I am not agree with this change, because it is performance relevant.
Before the change the "admin" could write the state directly. Almost every adapter runs as "admin".
And now before every write the readObject call will be done.

**Comment by foxriver76** [comment]
No doubt that it will have impact on the performance, at least for objects in redis. But it’s not a read Object thing like getObject and parse stuff, it only uses redis `exists` command. Furthermore I don’t see another way to implement such a check as desired in #230. A cache is not really possible in this scenario, because adapter.js is not informed about every object change in any case.

**Comment by GermanBluefox** [comment]
So may be the flag should be defined, e.g: adapterCaresItselfAboutStatesAndObjects and if it exists, so do not check the objects. I would use such a flag in modbus, s7, lcn, opcua and some others high performance adaprers

**Comment by foxriver76** [comment]
You mean a flag at Adapter init (options object passed to adapter.js)? I also thought about something like this as a possible solution - we could also default to disable the check and adapter could define strict mode e.g. `options.strict` true if he wants the check, but then nearly no one will use it - but looking at it as a flag used during testing would make sense too. 
Unfortunately we have no performance tests yet to see the real impact of this change.

Any other ideas? @Apollon77 @AlCalzone

**Comment by Apollon77** [comment]
I also had a long thought about that ... The "decentral" DBs we have in the meantime makes this very problematic because of all the reasons discussed above. I like the idea of an adapter "Option" like "strictObjectChecks" which can be set to false for adapters that know what they are doing and have this additional security for all other adapters

**Comment by GermanBluefox** [comment]
LGTM

**Pull request merged**
