### PR TITLE
do not crash controller if invalid pattern scanned in db

### LINKED ISSUE #2613: [bug]: View/attempted delete of channel with non-ascii character crashes Admin (appears to cause whole IOB restart)
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I was doing a bit of work on smartmeter and as part of that some channels with non-ascii characters were created in error by that adatper. Eg:

```JSON
{
  "type": "channel",
  "common": {
    "name": "0617641392\u0002"
  },
  "native": {},
  "from": "system.adapter.smartmeter.0",
  "user": "system.user.admin",
  "ts": 1679559871712,
  "_id": "smartmeter.0.0617641392\u0002",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Attempting to delete this channel with Admin causes it to crash.

Attempting to edit this channel (the above JSON) with Admin opens the edit window before crashing Admin adatper.

Both of the above also cause js-controller to restart too (see log below).

### To Reproduce

Appears to happen when trying to manipulate channels with with non-ascii characters in the name/id.

### Expected behavior

One should be able to view/edit channels as normal.

### Screenshots & Logfiles

```
2024-02-16 18:38:13.252  - ^[[31merror^[[39m: host.pl uncaught exception: The pattern "smartmeter.0.0617641392^B.*" is not a valid ID pattern
2024-02-16 18:38:13.253  - ^[[31merror^[[39m: host.pl Error: The pattern "smartmeter.0.0617641392^B.*" is not a valid ID pattern
    at Object.pattern2RegEx (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/tools.ts:2470:15)
    at ObjectsInMemoryServer._getKeys (/opt/iobroker/node_modules/@iobroker/db-objects-file/src/lib/objects/objectsInMemFileDB.js:850:36)
    at ObjectsInMemoryServer._handleScanOrKeys (/opt/iobroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:904:29)
    at RedisHandler.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:733:25)
    at RedisHandler.emit (node:events:513:28)
    at RedisHandler.emit (node:domain:489:12)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37)
    at processImmediate (node:internal/timers:466:21)
```

### Adapter version

6.13.16

### js-controller version

5.0.17

### Node version

v16.20.2

### Operating system

Raspbian GNU/Linux 11 (bullseye)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by foxriver76**
closes #2613

### CODE REVIEW

**Review by Apollon77 — APPROVED** [review]

**Review by raintonr — COMMENTED** [review]
I notice you changed `err` to `e`. Single letter variables are horrible because if you want to search for that variable... well... imagine how many times the letter `e` appears in this file.

**Comment by foxriver76** [comment]
> I notice you changed `err` to `e`. Single letter variables are horrible because if you want to search for that variable... well... imagine how many times the letter `e` appears in this file.

Lol

**Comment by raintonr** [comment]
> Lol

Guess you haven't had a giant mess of code full of such variables dumped in your lap and been asked to maintain it? I can assure you it's not funny.

**Comment by foxriver76** [comment]
It is our Common approach for use in catch and only in catch and you can find these easily as you don’t use 100 Lines of Code in catch. Anyway thanks for your input.

**Comment by raintonr** [comment]
Yes, I know. And I also know with a modern IDE it really shouldn't matter (although sometimes in our work we don't have access to our preferred tools). My point is that it's good programming practice to name variables meaningfully. It's also good programming practice that when fixing something one should not to touch things that don't actually need changing.

**Comment by foxriver76** [comment]
And it is good style to stick to practices the team has agreed on and this is really not a problem for us, you likely won't find this in other places. I basically agree to your second point, however, if we would stick to this the controller would still be in a state from like five years ago and trust me that is nothing someone would have want. 

If you are that interested in the code of the controller you might should think about taking over some issues and contributing, else thanks for your opinion - but the people working on this repository should be fine with code and workflow. So please don't waste your own valuable and my time discussing practices here.

**Pull request merged**
