### PR TITLE
show combined changelog on upgrade via cli

### LINKED ISSUE #541: Show „combined changelog“ when upgrading adapter
We should show a combined Changelog like in admin also on upgrades on command line. 
For Single upgrades we also might wait for a key press before continuing (could be overwritten by a force parameter). 

We need to make sure not to break updating from admin because if this (so maybe without the keypress :-( )

### PR DESCRIPTION
**Pull request by foxriver76**
- you can bypass this by --y flag
- if output isnt a tty check is bypassed automatically
- this is meant for v3.1
- closes #541 

Example:
```
moritz@moritz-XPS-13-9360:~/workspaces/ioBroker.js-controller$ iob upgrade hm-rega@2.6.2

This downgrade of "hm-rega" will at least remove the following changes:
==========================================================================
-> 2.6.4
we are now using iobroker file storage for regascripts
==========================================================================

Would you like to upgrade hm-rega from @2.6.4 to @2.6.2 now? [(y)es, (n)o]: 
```

and 

```
moritz@moritz-XPS-13-9360:~/workspaces/ioBroker.js-controller$ iob upgrade hm-rega

This upgrade of "hm-rega" will at least introduce the following changes:
==========================================================================
-> 2.6.4:
we are now using iobroker file storage for regascripts

-> 2.6.2:
minor fix on CCU object

-> 2.6.1:
added Sentry plugin support

-> 2.5.5:
logging of script name added, when script is still in pending queue

-> 2.5.4:
made port fully configurable also with https enabled

-> 2.5.3:
improved error handling in edge cases and more verbose logging on errors
==========================================================================

Would you like to upgrade hm-rega from @2.5.2 to @2.6.4 now? [(y)es, (n)o]: 
```

### CODE REVIEW

**Comment by Apollon77** [comment]
cooool

**Comment by AlCalzone** [comment]
I'll do a code review later. Two thoughts:
* I think "at least" is unnecessary
* Would it make sense to show the translated changelog if a user has configured ioBroker to a different locale than english?

**Comment by foxriver76** [comment]
>     * I think "at least" is unnecessary
My thoughts here are, that the news field is restricted to I think about 15 news. Thus, it can be that some news already have been removed.

>     * Would it make sense to show the translated changelog if a user has configured ioBroker to a different locale than english?

Whole cli stuff is in English, hence I stuck to it. However, we could also read `system.config` easily and get current language settings. What's your opinion @Apollon77?

**Comment by AlCalzone** [comment]
> My thoughts here are, that the news field is restricted to I think about 15 news. Thus, it can be that some news already have been removed.

Its 20, but good thought. Maybe only show "at least" (or "and maybe others") when the old version (or target version on downgrade) is no longer in the news list?

> Whole cli stuff is in English, hence I stuck to it.

Sounds logical. Translation is probably something for a future PR. At least in the refactored CLI classes I've collected all messages in one place.

**Pull request merged**
