### PR TITLE
Fix missing this reference in cliHost.js

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes: #355

### CODE REVIEW

**Comment by AlCalzone** [comment]
We should probably backport this to 1.5.x

**Comment by Apollon77** [comment]
verified

**Comment by AlCalzone** [comment]
So it works?

**Comment by Apollon77** [comment]
yes

**Comment by GermanBluefox** [comment]
Cannot find this code in 1.5.x

**Comment by AlCalzone** [comment]
Oh yeah you are right. I added it in 1.6-dev

**Pull request merged**
