### PR TITLE
fix schedule adapters stoppage being logged as error

### LINKED ISSUE #498: scheduled restarts should not log "error" on process termination
```
2019-10-11 02:00:00.019  - ESC[32minfoESC[39m: cloud.0 (2024) Scheduled restart.
2019-10-11 02:00:00.045  - ESC[32minfoESC[39m: cloud.0 (2024) Connection changed: io client disconnect
2019-10-11 02:00:00.047  - ESC[32minfoESC[39m: cloud.0 (2024) Connection lost
2019-10-11 02:00:00.068  - ESC[32minfoESC[39m: host.io1 instance system.adapter.weatherunderground.2 started with pid 18485
2019-10-11 02:00:00.077  - ESC[32minfoESC[39m: javascript.0 (1994) script.js.Watchdogs.Adapter-Connections: DETECT: Connection-Status of Adapter cloud.0 (pro) changed to false
2019-10-11 02:00:00.277  - ESC[31merrorESC[39m: host.io1 instance system.adapter.cloud.0 terminated with code 156 (156)
2019-10-11 02:00:00.284  - ESC[32minfoESC[39m: host.io1 Restart adapter system.adapter.cloud.0 because enabled
2019-10-11 02:00:01.336  - ESC[32minfoESC[39m: host.io1 instance system.adapter.cloud.0 started with pid 18492

```

### PR DESCRIPTION
**Pull request by foxriver76**
- remove magic HEX value
- fixes #498 
- as mentioned in the issue we have the problem, that error codes are emitted as (256 + exit code % 256), thus the exit code is emitted as 156 when using -100. The comparison is done by the constant referred in the exitCodes file, thus -100 === 156 obviously fails and thus it is logged on error level.
- I've also removed the HEX Code and the related comparison in consultation with Ingo, if its needed, please let us know @GermanBluefox

### CODE REVIEW

**Comment by Apollon77** [comment]
@foxriver76 looks ok for me. Di you verified that on schedule the restart will still happen directly after stop without waiting 30s?

**Comment by foxriver76** [comment]
works
```
2020-03-12 07:45:00.003  - info: info.0 (9705) Scheduled restart.
--
2020-03-12 07:45:00.003  - info: info.0 (9705) cleaned everything up...
2020-03-12 07:45:00.006  - info: info.0 (9705) terminating
2020-03-12 07:45:00.007  - info: info.0 (9705) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2020-03-12 07:45:00.514  - info: host.moritz-XPS-13-9360 instance system.adapter.info.0 scheduled normal terminated and will be started anew.
2020-03-12 07:45:00.514  - info: host.moritz-XPS-13-9360 Restart adapter system.adapter.info.0 because enabled
2020-03-12 07:45:01.519  - info: host.moritz-XPS-13-9360 instance system.adapter.info.0 started with pid 10490
2020-03-12 07:45:02.620  - info: info.0 (10490) starting. Version 1.5.7 in /opt/iobroker/node_modules/iobroker.info, node: v10.19.0, js-controller: 3.0.0
```

**Comment by Apollon77** [comment]
Nice! Thank you

**Comment by Apollon77** [comment]
Hm ... thinking again I'm not sure ... could it be that these "overrun" codes can happen on Windows?

**Comment by foxriver76** [comment]
As mentioned in Telegram, the Exit Code is no longer negative

**Pull request merged**
