### PR TITLE
Add disableDataReporting to instance common

### PR DESCRIPTION
**Pull request by GermanBluefox**

### CODE REVIEW

**Comment by foxriver76** [comment]
We already have the state `${this.instanceId}.plugins.sentry.enabled` for this… isn’t it redundant?

**Comment by Apollon77** [comment]
According to code https://github.com/ioBroker/plugin-sentry/blob/master/index.js#L49C45-L49C81 only the host object shpuld have this!

**Comment by foxriver76** [comment]
Yes it makes no sense to have it as per instance we already have the state from my point of view. Please no redundancy here

**Comment by Apollon77** [comment]
There should be no reason for someone to just allow Sentry for single instaces ... honestly ... if someone do not want it he disables it per host/systerm ... thats enough. we do not need more granularity here.

If needed as info for e.g. the UI then we could create a system.-adapter.name.X.disabledReporting state which is set correctly, so that a UI do not need to search the host ad such to get it

**Comment by foxriver76** [comment]
> If needed as info for e.g. the UI then we could create a system.-adapter.name.X.disabledReporting state which is set correctly, so that a UI do not need to search the host ad such to get it

We already have a state for every plugin.. see my first comment.

**Comment by foxriver76** [comment]
I see, admin uses this when clicking on the UI so instead of setting the state it uses this self defined flag. We should change admin behavior to get rid of this redundancy.

**Pull request closed without merging**
