### PR TITLE
Jsonl default in conf

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by Apollon77** [comment]
WAIT

**Comment by foxriver76** [comment]
> WAIT

🍵

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/ioBroker.js-controller/issues/1707

**Comment by Apollon77** [comment]
@foxriver76 Could you add the "remove of "no migration for CI" to this PR? Then we have all in one place :-)

**Comment by foxriver76** [comment]
done

**Pull request merged**
