### PR TITLE
do not allow access to adapter.states and adapter.objects anymore

### PR DESCRIPTION
**Pull request by foxriver76**
- provide backward shim for the two used methods `getObjectList` and `getObjectView`

### CODE REVIEW

**Comment by Apollon77** [comment]
you also ned to adjust testing, minimum
test/lib/testAdapter.js:226+227 ;-)

We will hold this back for 2.3 and can be merged once 2.2.x is out

**Comment by foxriver76** [comment]
True, fogot to execute the tests. ;-)

**Comment by foxriver76** [comment]
But https://github.com/ioBroker/ioBroker.js-controller/pull/614/files#diff-92b80e8b4185c3e7c279a8e990a162e5L227 has to exist, because we are currently providing an adapter.objects which is used as a backward compatibility shim and provides `getObjectList` and `getObjectView`.

**Comment by AlCalzone** [comment]
> I implemented it on debug level for now

I would do it now, because that is something that will likely be forgotten.

**Comment by foxriver76** [comment]
Done. Hopefully it won't be too annoying for our users.

**Comment by AlCalzone** [comment]
Many adapters are already fixed and those messages put pressure on those devs who haven't yet. :)

**Comment by GermanBluefox** [comment]
@foxriver76 I saw that you fixed many adapters with this change. Thank you :)
The only Problem what I have is, that I have a plan to rewrite adapter to classes and class has no private attributes..... but

But at least when it will happen no one driver will use adapter.objects and this will be mainstream.
If no one has anything against it I will merge it.

**Comment by foxriver76** [comment]
You can still use global variables in classes - it’s not the most beautiful way but it prevents access from outside. IMHO the current implementation is like a class just w.o. ES6 classes - converting it to ES6 class shouldn’t change anything about it’s behavior.

**Comment by Apollon77** [comment]
Please DO NOT MERGE before we released 2.2.x to stable. Please see tags!!

We should have an issue for the adapter rewrite to classes ;-)

**Comment by AlCalzone** [comment]
There are definitely ways to get true private fields in classes, although they are a bit ugly. Weak Map or locally defined symbols as the field names.
Or wait for node.js 12 which has support for private fields (this.#field)

**Comment by AlCalzone** [comment]
Global properties have issues when you require the module twice

**Comment by Apollon77** [comment]
That private methods are not available is a current problem in general in ES6 classes, so we can only use the "standard way" to use conventions like "all private stuff starts with an underscore or such.

In the special case of adapter base class in our project globald would work ok-ish because double require is normally only relevant in compact mode and here the require cash will be cleared before a second adapter is started and this should avoid the problem here.

**Comment by Apollon77** [comment]
> There are definitely ways to get true private fields in classes, although they are a bit ugly. Weak Map or locally defined symbols as the field names.

Only a bit ugly? ;-)) In my eyes unusable because they add that much overhead to coding that it do not work in my eyes. 

ndejs 12? Is already here ... is it really already in there?

**Comment by foxriver76** [comment]
I guess we cannot force our users to use nodejs12 yet, many users are still running node 8 even tough its EOL now. Furthermore, using underscore notation may be a good practice but adapter devs could still easily bypass some functionalities by using objects/states directly. Also many adapter devs are new to Nodejs or even programming and may not be aware of this best practice and its meaning. 

I would go for the current solution provided in this PR and wait until we can require our users to use nodejs12 and then rewrite adapter.js to 'real classes'. Note, that we really want to prevent adapter devs from accessing these methods and not only recommend it by using naming conventions.

**Comment by AlCalzone** [comment]
> ndejs 12? Is already here ... is it really already in there?

YES :) => https://node.green/

grafik

**Comment by Apollon77** [comment]
And we need to check which adapters still do not work with nodejs 12 because of dependency issues!!

**Comment by GermanBluefox** [comment]
> Please DO NOT MERGE before we released 2.2.x to stable. Please see tags!!
> 
> We should have an issue for the adapter rewrite to classes ;-)

Had not see them at all.... Now I see.

**Comment by GermanBluefox** [comment]
2.2.x released. Merge?

**Pull request merged**
