### PR TITLE
Fix npm version preinstall check

### PR DESCRIPTION
**Pull request by AlCalzone**
in case `npm -v` fails. Should fix part of the issue here: https://forum.iobroker.net/viewtopic.php?p=133514#p133514

### CODE REVIEW

**Comment by GermanBluefox** [comment]
THank you

**Comment by GermanBluefox** [comment]
@AlCalzone Question for using the new stuff.

Does node4 has following features?
1. let
2. const
3. lambda functions: () => {function body}
4. APromises: new Promise((resolve, reject) => {})
5. `text ${someVariable}`
6. Objects {var1, var2, var3: 'value'}
7. let [start, end] = str.split('.');
8. let {start, end} = getMeTheObjectWithStartEnd();

**Comment by AlCalzone** [comment]
With `‘use strict’`:
1-5: yes
6: pretty sure
The rest: let me check later

**Comment by AlCalzone** [comment]
6: yes => http://node.green/#ES2015-syntax-object-literal-extensions-shorthand-properties
7/8 are only available in node6+ => http://node.green/#ES2015-syntax-destructuring--declarations

**Comment by GermanBluefox** [comment]
Thank you. So I will use the new stuff too.

2018-03-15 15:25 GMT+01:00 AlCalzone <notifications@github.com>:

**Pull request merged**
