### PR TITLE
auto check PRs via eslint

### PR DESCRIPTION
**Pull request by foxriver76**
- this partially addresses #257 
- example: https://github.com/foxriver76/ioBroker.js-controller/pull/3/files

### CODE REVIEW

**Comment by Apollon77** [comment]
iiiinteresting ... Opinions?

**Comment by AlCalzone** [comment]
Can we not just run eslint on the repo? Config files are there already, so it's a question of installing the dev dependency (if not already done) and executing it

**Comment by foxriver76** [comment]
The GitHub action only checks newly added code lines which is pretty nice in my opinion. Also the PR will be commented. Also the actions is of course taking respect to our eslintrc config.

**Comment by AlCalzone** [comment]
Ok that is cool

**Comment by Apollon77** [comment]
Ok, lets try it ...

**Pull request merged**
