### PR TITLE
Upgrade repo from insecure http://download.iobroker.net to secure https://repo.iobroker.live

### PR DESCRIPTION
**Pull request by jpawlowski**
Not sure this is still intentional, but it seems obvious to me that the dedicated subdomain and TLS-secured repo URL (which is also CDN powered) makes more sense to use.

This also improves security as also the redirect from http://download.iobroker.net to https://repo.iobroker.live still leaves room for MITM attacks to sneak in other adapters or potentially redirect to a different source.

This PR will upgrade to the new URL, seems like a pretty minor patch to me that might have simply been forgotten somewhere in the past when repo.iobroker.live was set up.

### CODE REVIEW

**Comment by jpawlowski** [comment]
Apologies for the JSON files being "prettified" by VScode Prettier. Let me know if you insist on the original format.

**Comment by Apollon77** [comment]
Please revert all these prettier formatting changes ... In general we need to discuss that because it was intentionally that it is http and also that it is the domain that was in there!

@GermanBluefox ?

**Comment by jpawlowski** [comment]
To me it seems this repository comes with some presets for the Prettier extension in VScode ([.prettierignore](https://github.com/ioBroker/ioBroker.js-controller/blob/master/.prettierignore) and [.prettierrc.json](https://github.com/ioBroker/ioBroker.js-controller/blob/master/.prettierrc.json)). There might be incompatibilities with the settings you put in [.eslintrc.js](https://github.com/ioBroker/ioBroker.js-controller/blob/master/.eslintrc.js), resulting in this failure.

If you want me to fix the formatting, I suggest that this gets sorted out in the first place? I didn't change the formatting intentionally but simply followed what is configured for this repo.

**Comment by jpawlowski** [comment]
> In general we need to discuss that because it was intentionally that it is http and also that it is the domain that was in there!

You could also enable HTTP on download.iobroker.net (which currently lacks a proper certificate) but regardless, the entry point does not benefit from the CDN afterwards so... either enable the CDN for iobroker.net as well (which I assume was also intentionally left out?) or to make a simple change as iobroker.live is also under your control (presumably your main objective?).

**Comment by GermanBluefox** [comment]
I want to keep download.iobroker.net, as I can forward from this address anywhere (ngunx). And ioBroker.live is uncontrollable because it is "ready to use" web service

**Comment by jpawlowski** [comment]
Okay. So... download.iobroker.net will be enabled for TLS then?

**Comment by jpawlowski** [comment]
A side note:

I got indications that using https instead of http for the update URLs might lead to a crash of the js-controller when processing the daily update (but not when triggering an explicit update check using the terminal console).

This is how it looks like and I believe it happens daily (still need to monitor a few more days):

image

Also linking my issue report at https://github.com/buanet/ioBroker.docker/issues/269

**Comment by Apollon77** [comment]
How you come to the idea that this is connected to HTTP?

This errors are "easy": Soehow the js-controller crashes in this case becaus ethe log states that the DB connections gone away. SoFind out WHAT and WHY the controller got killed ... and please do not link issues taht do not have anything in common

**Comment by Apollon77** [comment]
We stay as is for now ... yes there is a risk about "man in the middle" attacks in the local network. This is just an issue if really someone is already in your system and was able to somehow proxy all the requests or redirect it in your DNS ...

**Pull request closed without merging**
