### PR TITLE
Replace function*/yield with async/await

### PR DESCRIPTION
**Pull request by AlCalzone**
Now that we got rid of Node 6, we can finally use `async/await` :heart_eyes: 
This PR replaces all instances where we used the generator function + yield pattern that emulated async/wait on old node versions.

### CODE REVIEW

**Comment by Apollon77** [comment]
Merge postponed till we kick off 2.1

**Comment by GermanBluefox** [comment]
Very well, because I still do not understand yield.

**Comment by AlCalzone** [comment]
It's basically the same as await but with a more complicated syntax for the async function definition.

**Comment by Apollon77** [comment]
@AlCalzone COuld you do a run and solve the conflicts, then we can merge into master now. SOrry for the long time

**Comment by AlCalzone** [comment]
Done!

**Pull request merged**
