### PR TITLE
we allow user as optional state object  property

### PR DESCRIPTION
**Pull request by foxriver76**

### CODE REVIEW

**Comment by AlCalzone** [comment]
This should also be added to @types/iobroker

**Comment by foxriver76** [comment]
Question is does it make sense to allow this or disallow and adjust documentation.

**Comment by AlCalzone** [comment]
I'm not sure. @Apollon77 @GermanBluefox ?

**Comment by Apollon77** [comment]
I think this is not allowed  I check what frankjoke stores there

**Comment by Apollon77** [comment]
Ok https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md#states is right then :-)

**Comment by Apollon77** [comment]
> This should also be added to @types/iobroker
@AlCalzone Could you take care?

**Comment by AlCalzone** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43844

**Pull request merged**
