### PR TITLE
Review stuff that was too late for #1150

### PR DESCRIPTION
**Pull request by raintonr**

### CODE REVIEW

**Comment by Apollon77** [comment]
Is the PR outdated? there were plenty code c hanges afterthe original merge and the PR would revert many of them ... don't know if this is a good idea

**Comment by raintonr** [comment]
> Is the PR outdated? there were plenty code c hanges afterthe original merge and the PR would revert many of them ... don't know if this is a good idea

It was when I opened it, but noticed that and a few minutes ago merged in master. Should only be the single file changed now. It looks a lot because the diff hasn't noticed many changes just indentation.

**Comment by Apollon77** [comment]
check the diff here ... way more then a line and intends :-))

**Comment by raintonr** [comment]
> check the diff here ... way more then a line and intends :-))

Oh... I see. Someone messed with my shiny new commits :( Re-merged. If you don't like that, throw this PR away and I'll have to bin my branch and start again.

**Comment by raintonr** [comment]
> check the diff here ... way more then a line and intends :-))

P.S. This stuff around the notify function is hideous - I left it way cleaner: https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/letsencrypt.js#L56

**Comment by raintonr** [comment]
Actually... forget this, I do it again cleaner.

**Pull request closed without merging**
