### PR TITLE
migrated ci tests to github actions

### LINKED ISSUE #664: Check and implement GitHub Actions
... especially Redis support for all test cases

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #664

### CODE REVIEW

**Comment by AlCalzone** [comment]
Looks good. Two questions:
1. What's the "After Success (Linux)" step for? Just for our information?
2. Should we delete the Travis/AppVeyor files as part of this PR?

**Comment by foxriver76** [comment]
1. It’s Migration of this part https://github.com/ioBroker/ioBroker.js-controller/blob/4c1a6f3d639bfb9aa00c67ba29e393914fcc9521/.travis.yml#L29 I guess it is informative only, however `npm audit` can exit with code 1 regarding the given audit level. Maybe Ingo knows more about this step. 

2. I would appreciate it. @Apollon77?

**Comment by AlCalzone** [comment]
> exit with code 1

Then we should make this step not fail the build IMO

**Comment by foxriver76** [comment]
AFAIK there is no way currently to perform a neutral task, thus I be configured a higher audit level. We can raise the Audi level to critical or make it pass all the time using or in the command, executing something which will always succeed in the or clause.

**Comment by AlCalzone** [comment]
> there is no way currently to perform a neutral task

There is: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

**Comment by foxriver76** [comment]
Interestingly this works. I've interpreted it, that it still would mark the step as failure but continues with the execution of the next steps instead of canceling then.

**Comment by Apollon77** [comment]
Yes the npm audit was info only from times before dependabot and githb security alert existed :_) so we can also kill it

**Comment by Apollon77** [comment]
I'm ok with removing travis/appveyor

**Comment by foxriver76** [comment]
I've removed the `After Success` Step and configs for travis and appveyor (appveyor fails because of missing config now)

**Pull request merged**
