### PR TITLE
Define API interface of the Objects and States DB

### PR DESCRIPTION
**Pull request by AlCalzone**
With this PR we now have a type definition for the objects and states DB and use them whereever possible. Draft for now because some methods in the States DB are missing and I found a few bugs in @types/iobroker, which need to be squashed first.

### CODE REVIEW

**Comment by AlCalzone** [comment]
Blocked by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43832

**Comment by AlCalzone** [comment]
Using the typings in JS-Controller is a very valuable dogfooding exercise. I've found the next two things to be improved:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44110
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44112

**Comment by AlCalzone** [comment]
@Apollon77 @foxriver76
I would like to use this PR and discuss some of my findings and either fix some potential bugs in JS-Controller or correct the type declarations.
Let's start with `main.js`:

https://github.com/ioBroker/ioBroker.js-controller/blob/082dfbb861519a07e9f11a2e76c6aaffbf8d2fa3/main.js#L852-L857
According to the type definitions I made a while back, the `value` of a results row of `getObjectView` can be `null`. Is this correct? If so, there are a bunch of locations where we don't check for that.

---

https://github.com/ioBroker/ioBroker.js-controller/blob/082dfbb861519a07e9f11a2e76c6aaffbf8d2fa3/main.js#L913-L914
https://github.com/ioBroker/ioBroker.js-controller/blob/eb93196d573e491397d0c9f211f03356b92f9fb8/main.js#L2439-L2440

If the callback is called with an "error" from `checkObjectRights`, `err` is a string and the above lines will cause a crash.
https://github.com/ioBroker/ioBroker.js-controller/blob/082dfbb861519a07e9f11a2e76c6aaffbf8d2fa3/lib/objects/objectsUtils.js#L603-L611
https://github.com/ioBroker/ioBroker.js-controller/blob/082dfbb861519a07e9f11a2e76c6aaffbf8d2fa3/lib/objects/objectsUtils.js#L25-L27

---

https://github.com/ioBroker/ioBroker.js-controller/blob/eb93196d573e491397d0c9f211f03356b92f9fb8/main.js#L1877
`systemConfig` may be undefined here.

---

https://github.com/ioBroker/ioBroker.js-controller/blob/eb93196d573e491397d0c9f211f03356b92f9fb8/main.js#L2642-L2643
`adapterDir` may be undefined, in this case `fs.existsSync(adapterDir)` is false and the if clause will be taken. Is this intended?

Same thing here:
https://github.com/ioBroker/ioBroker.js-controller/blob/eb93196d573e491397d0c9f211f03356b92f9fb8/main.js#L3076-L3077
In fact, the remaining code assumes that `adapterDir_` is defined.

**Comment by foxriver76** [comment]
> If the callback is called with an "error" from `checkObjectRights`, `err` is a string and the above lines will cause a crash.

We should then return an error also in utils.checkObjectRights or better use our maybeCallback function

**Comment by foxriver76** [comment]
>  `adapterDir` may be undefined, in this case `fs.existsSync(adapterDir)` is false and the if clause will be taken. Is this intended?

I think so because the if clause code tries to install the adapter, because it seems not to exist.

**Comment by AlCalzone** [comment]
>  it seems to return

You're right, I missed that.

**Comment by foxriver76** [comment]
> According to the type definitions I made a while back, the `value` of a results row of `getObjectView` can be `null`. Is this correct? If so, there are a bunch of locations where we don't check for that.

I found one scenario where this could happen: 
https://github.com/ioBroker/ioBroker.objects-redis/blob/a266b8ff4196c73ef596627625aa282780488fe7/lib/objects/objectsInRedis.js#L2924

But imo this type of error handling is pretty ugly, returning an id called 'parseError'. We should filter this ids out.

**Comment by AlCalzone** [comment]
> But imo this type of error handling is pretty ugly, returning an id called 'parseError'. We should filter this ids out.

Agreed

**Comment by AlCalzone** [comment]
I've done some more changes to reduce the number of red squiggles in the editor and I have PRs pending to update @types/iobroker to more correct versions.

Once we have discussed the above issues, I'll move on to other files with lots of red. TODOs:

- [ ] value is null
- [x] strings as errors (PR is up)
- [ ] Is the behavior correct when adapterDir is undefined? @Apollon77?
- [ ] systemConfig undefined

**Comment by AlCalzone** [comment]
Found more:
https://github.com/ioBroker/ioBroker.js-controller/blob/6deb9337ea672bd4192aad83a9f9ff969c53a17d/lib/setup.js#L1162
grafik
If I'm not mistaken, the first argument should be part of the object ID (e.g. `admin.0`), not common.name (which can be an object as we learned today). 
Correct? If so, we need to fix a couple of locations in setup.js

**Pull request closed without merging**
