### PR TITLE
add docs for redis sim functionalities

### LINKED ISSUE #1454: document redis simulator functionalities
... to know what we support and what not

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1454

### CODE REVIEW

**Comment by foxriver76** [comment]
But due to the fact, that it's only an overview for the controller devs, it should be what we wanted @Apollon77?

**Comment by AlCalzone** [comment]
I'd still add the link you posted for anyone who wants to dig deeper.

**Comment by Apollon77** [comment]
I would add the "namespaces" that we support for states and objects because this is really special happed inside - especially for Objects-DB where we have meta keys, file and objects keys ... Rest is cool!

**Comment by foxriver76** [comment]
Will add it, if you find some time you can also push to the branch

**Comment by Apollon77** [comment]
@foxriver76 That feels complete to my rememberings

**Pull request merged**
