### PR TITLE
introduce possibility to use different states for alias read and write

### LINKED ISSUE #565: Erweiterung Alias Funktionalität im Hinblick auf HM-Ip Geräte (Separate ID für Read und Write)
Gerade für HM-IP geräte würde sich eine Funktionale Erweiterung der Alias Funktionalität anbieten:
Diese Geräte haben einen separaten Datenpunkt für z.B. Dimmwert (beispielsweise in Kanal 3)
und einen separaten Datenpunkt zum setzen eines Dimmwertes (beispielsweise Kanal 4)

Gut wäre in diesem Zusammenhang die Möglichkeit, nicht nur eine read / write funktion zum konverteren angeben zu können sondern die optinale Möglichkeit, eine aliasID für einen ReadDP und einen aliasDP für einen WriteDP anzugeben.

Ich nutze diese Möglichkeit heute schon in meinem eigenen Wrapper-Script,  welches die Möglichkeit vorsieht, unterscheidliche Datenpunkte für read und write anzugeben.

Damit wäre es dann auch möglich, "normale" Widgets z.B. Für Lampen an diesen AliasDP anzubinden, wibei dieser AliasDP sich dann  den Istzustand aud dem readAlias holen würde und bei Änderung den Write Alias beschreiben würden.

Black

### PR DESCRIPTION
**Pull request by foxriver76**
Alias id can also be an `object` from now on containing properties `read` and `write`. When user does something like `setState(aliasId)` the state will be forwarded to the `write` id. When the `read` id is changed, the state will also be set to the alias state. This would close #565.

For this to work, we have to adjust `objectsInRedis` too.

### CODE REVIEW

**Comment by Apollon77** [comment]
I did a check ... looks good so far and aslo a test is added! Great.

It is a lot of duplicated code ... but this was that way also before ... ;-)

**Comment by GermanBluefox** [comment]
Actually this should be solved via devices.
Every see device has SET and ACTUAL date point....
But the idea is interesting.

**Comment by foxriver76** [comment]
As described in #565 it is desired to combine set and actual sates in one state in some situations, e.g for visualizations of hmip shutters.

**Comment by foxriver76** [comment]
> It is a lot of duplicated code ... but this was that way also before ... ;-)

I can wrap some duplicate code into functions, but first we should discuss about the functionality.

**Comment by Apollon77** [comment]
LGTM

**Pull request merged**
