### PR TITLE
Provide ESM and CJS exports for all packages

### PR DESCRIPTION
**Pull request by foxriver76**
- addresses #1379

### CODE REVIEW

**Comment by foxriver76** [comment]
@Apollon77 any chance to review this in the near future?

**Review by Apollon77 — APPROVED** [review]
Should we also add typesVersions? for even better support ?

see https://github.com/project-chip/matter.js/blob/main/packages/matter.js/package.json#L143-L144

**Comment by foxriver76** [comment]
> Should we also add typesVersions? for even better support ?
> 
> see https://github.com/project-chip/matter.js/blob/main/packages/matter.js/package.json#L143-L144

I think we have it for subpath exports if needed. https://github.com/ioBroker/ioBroker.js-controller/blob/8d8cf7a10957f984f74f630cfbfd111496517a54/packages/db-base/package.json#L44

**Comment by foxriver76** [comment]
note: tests are failing due to api extractor needs fix

**Pull request merged**
