### PR TITLE
Optimize build process

### PR DESCRIPTION
**Pull request by AlCalzone**
The first set of changes brings the build time for JS-Controller down to 12s for a rebuild without changes, compared to ~1m10s previously, simply by disabling the prebuild script. Because we may need to force a clean build in some cases, I propose keeping the prebuild script around as `npm run clean`.

I'll investigate further with TS Project References.

**Edit:** While setting them up is tedious (effectively mirroring the dependencies into both tsconfig files per folder), they are **FAST**.
Down to 19s on a clean build (from 1m10s). Down to 1s on a rebuild (from 12s).

### CODE REVIEW

**Comment by AlCalzone** [comment]
draft again, since rebuilding `common` causes some error

**Comment by AlCalzone** [comment]
@foxriver76 we have a circular dependency through packages, causing output to be treated as input files. All paths are relative to `packages/common`:
```
build/lib/common/tools.d.ts
  Imported via '@iobroker/js-controller-common/tools' from file '../db-objects-redis/build/lib/objects/objectsInRedisClient.d.ts' with packageId '@iobroker/js-controller-common/build/lib/common/tools.d.ts@5.0.0-alpha.0-20230217-a0c54039'
  Imported via '@iobroker/js-controller-common/tools' from file '../db-base/build/lib/inMemFileDB.d.ts' with packageId '@iobroker/js-controller-common/build/lib/common/tools.d.ts@5.0.0-alpha.0-20230217-a0c54039'
../db-base/build/lib/inMemFileDB.d.ts
  Imported via '@iobroker/db-base/inMemFileDB' from file '../db-objects-redis/build/lib/objects/objectsInRedisClient.d.ts' with packageId '@iobroker/db-base/build/lib/inMemFileDB.d.ts@5.0.0-alpha.0-20230217-a0c54039'
../db-objects-redis/build/lib/objects/objectsInRedisClient.d.ts
  Imported via './lib/objects/objectsInRedisClient' from file '../db-objects-redis/build/index.d.ts'
../db-objects-redis/build/index.d.ts
  Imported via '@iobroker/db-objects-redis' from file '../types/build/types.d.ts' with packageId '@iobroker/db-objects-redis/build/index.d.ts@5.0.0-alpha.0-20230217-a0c54039'
../types/build/types.d.ts
  Imported via './build/types' from file '../types/index.d.ts'
../types/index.d.ts
  Entry point of type library '@iobroker/types' specified in compilerOptions with packageId '@iobroker/types/index.d.ts@5.0.0-alpha.0-20230217-a0c54039'
```

**Comment by AlCalzone** [comment]
This is no good:
grafik

The types package can't be importing anything, it should be the one providing the types.

**Comment by AlCalzone** [comment]
Solved it. @foxriver76 you may want to look at what I did in the last commit and keep it in mind for shared types you add in the future

**Review by foxriver76 — APPROVED** [review]

**Comment by foxriver76** [comment]
Can you resolve conflicts and ping me, then I  will merge or you can merge

**Pull request merged**
