### PR TITLE
added Docker version information for the official Docker image

### PR DESCRIPTION
**Pull request by o0shojo0o**

### CODE REVIEW

**Comment by foxriver76** [comment]
Thanks.

multiple things: 

1. please explain for what this is needed it is used nowhere in controller
2. second why is `getDockerInformation` not sufficient? It contains all of the information in a more structured api
3. if you need it in an adapter better think about exporting in Adapter Core like https://github.com/ioBroker/adapter-core/blob/1111d35cbcc0c9e05b1aadd71fdcbd02d09340ff/src/controllerTools.ts#L159

**Comment by o0shojo0o** [comment]
Hi this information is displayed under the Admin -> Hosts.  
image

**Comment by foxriver76** [comment]
Ah haven’t seen the Adaption of getHostInfo..

**Comment by o0shojo0o** [comment]
Yes sorry I could have mentioned ;)

**Comment by foxriver76** [comment]
I am not sure about changing the docker indicator to a string with version, as the other platforms also have no version here in and the same information is sent to the diag backend for our statistics, which make it harder to analyze with that non structured string. I can propose a change without breaking this, will also need some admin adaption, but it would be minimal. It would be better if we not change a string here for visualization purposes, we should provide structured data and admin can then decide how to visualize it.

**Comment by o0shojo0o** [comment]
Yes I agree, thanks for the newly created issues and customizations!

**Pull request closed without merging**
