### PR TITLE
[wip] typescript

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
todo:
fix path to renewal.conf.tpl in letsencryptStore.js

**Comment by jogibear9988** [comment]
todo:
move preinstallCheck.js maybe out of src to assets so it will be found by preinstallscript (or look what to so with it..)

**Comment by GermanBluefox** [comment]
I decided to not use a typescript in main ioBroker projects.
pros: 
- Typing will be checked by compilation

contras: 
- Input is higher for coders who want to develop the core

As an example I could take a look at pimatic, where coffescript was used. Now the coffescript is dead, and pimatic almost dead too....

**Comment by AlCalzone** [comment]
> As an example I could take a look at pimatic, where coffescript was used. Now the coffescript is dead, and pimatic almost dead too....

I completely understand the reasoning for not using it and I'm totally fine with it. But I can't let this argument stand. Unlike CoffeeScript, TypeScript won't be going anywhere soon, because it's too widely accepted and even included in many JS editors.

After all, we can just continue using JSDoc comments with method parameters. This offers great support for TS-powered editors at only the cost of 2-3 lines of comments. If it doesn't bother you, I will continue to do so (like I have done in the past). This way, everyone can simply opt-in.

**Comment by Apollon77** [comment]
I completely support the JSDoc and maybe also some time later it is right to switch to TS ...

**Pull request closed without merging**
