### PR TITLE
controller v5 node requirements

### LINKED ISSUE #2054: Adjust Minimum nodejs to 14.18.0+ and 16.0.0+
In order to always support the "node:" require prefix we need to set minimum nodejs versions to 14.18.0+ and 16.0.0+

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #2054
- anything else to do for #2054?

### CODE REVIEW

**Comment by Apollon77** [comment]
In fact all fine, we just need to this about communication because  if we merge that all adapters that still test nodejs 12 might break in testing? So we should communicate before merging.

Maybe also enhance something in installer ?

**Comment by foxriver76** [comment]
> So we should communicate before merging.

ack

> Maybe also enhance something in installer ?

Do we have a version check there? I am not sure. I am also not familiar with how npm is handling the engines field right now.

**Comment by Apollon77** [comment]
> Do we have a version check there?

For windows yes, Linux not :-) But for Linux we install Ndoejs 16

And in both cases we write the package.json and such with also the minimum node version in it ... so yes ... change for later

> I am also not familiar with how strict npm is handling the engines field right now.

In fact we enable npm strict mode on "non windows" systems,so it will be respected. But no idea about testing :-)

**Comment by Apollon77** [comment]
LGTM ... but before we merge this we should inform all devs :-)

**Review by Apollon77 — CHANGES_REQUESTED** [review]
because of #2120 we need to adjust this to : >= v16.4.0, v14.18.0

**Comment by foxriver76** [comment]
done

**Pull request merged**
