### PR TITLE
add instances info and compact info to diag

### LINKED ISSUE #1648: Enhance diag Data for db types and compact mode
We should enhance the sent diag data by
* db types to get a statistic of number of stae/object DB combinations as chart
* compactmode controler true/false
* number of compactmode instances (if enabled)
@GermanBluefox what do you think??

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1648

### CODE REVIEW

**Comment by foxriver76** [comment]
Adapters are listed, we could also list no instances as a property of adapter to show how many instances of each adapter and also compact instances grouped by adapter

**Comment by Apollon77** [comment]
Denke dafürt brauchen wir @GermanBluefox weil er ja mit den Daten was anfangen können muss und das Backend bereitstellt :-)

**Comment by Apollon77** [comment]
I think we do not need tze list of instances

**Comment by GermanBluefox** [comment]
> I think we do not need tze list of instances

We need the list of instances as we calculate with that at the end the usage of adapters

**Comment by GermanBluefox** [comment]
LGTM

**Pull request merged**
