### PR TITLE
fix npm install specialities

### PR DESCRIPTION
**Pull request by Apollon77**
* make sure to also allow weired exit code 1 from npm as success like in all other places too. This should fix cases where upload is missing or such when ioBroker thinks a second npm install is needed

* make sure to create the iob_npm.done file after the additional npm install because it is missing :-)

### CODE REVIEW

**Comment by Apollon77** [comment]
I analyzed the code a but and the "extra npm install" is done when the file iob_npm.done is not existing in the adapter directory. This file is created aftwer a normal install.
When the file is missing an additional "Npm install" is done ... I assume this is for "manually" created adapter directories OR for the "Zip File installs" where by defaukt no "npm" is in place when installing.

So I would leave the additional install in, but create the file when it is executed once ...

**Comment by AlCalzone** [comment]
I'm still not sure why we need a 2nd install and that file (#270), but the change looks good to me.

**Comment by Apollon77** [comment]
> I'm still not sure why we need a 2nd install and that file (#270)
In fact it is no second call in my eyes. The code normally make sure that on successfull install the iob_npm.done is created and so the extra install is never executed. (e.g. https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/setup/setupInstall.js#L377 ). This means in myeyes that the file normally should always exists as soon as someone installs correctly.
The file will not exist at the moment when you install via "npm" directly manually OR when "Zip iobroker install" is used (https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/setup/setupInstall.js#L214. - I did not even know that this is possible).

Especially in the second case there are only files unzipped and placed in a node_modules subfolder BUT NO npm call is issued.
My assumption is that this extra npm install was meaned for these kind of  installations (also pot. other planned release options that automatically "fully install" on first start (e.g. you only deliver the plain plugin files and deps will be installed on first start).

And because of the two above issues - exitcode 1 AND case because specisl file was never placed after the etxra install was performed we had this effect sometimes :-)
With this PR the extra install should only happen maximum once

**Comment by Apollon77** [comment]
@GermanBluefox maybe you have more insight if my assumptions are correct?

**Comment by AlCalzone** [comment]
> Especially in the second case there are only files unzipped and placed in a node_modules subfolder BUT NO npm call is issued.

I'm not sure this is still compatible with newer npm versions, if you remember our problems with the installer before we rebuilt it. Otherwise there's always the option to `npm install` from a local tarball.

**Comment by Apollon77** [comment]
I agree. So basic question for #270 is if we still ned that handling at all or can remove it. But this fix should make things better in any case :-)

**Comment by Apollon77** [comment]
@GermanBluefox maybe you have more insight if my assumptions are correct?

**Pull request merged**
