### PR TITLE
Replace JSON.stringify comparisons with built-in isDeepStrictEqual

### PR DESCRIPTION
**Pull request by AlCalzone**

### CODE REVIEW

**Comment by AlCalzone** [comment]
Test failures are on Node 8, which does not support this method yet.

**Comment by foxriver76** [comment]
Node 8 support is dropped anyway with controller 3

**Comment by Apollon77** [comment]
ok, travis fails because nodejs 8 ... why this is still checked ... hm ...

**Comment by Apollon77** [comment]
i kill it with my next commit

**Pull request merged**
