### PR TITLE
If no configuration found, or adapter was not properly installed, check it.

### PR DESCRIPTION
**Pull request by GermanBluefox**
You can reproduce this error when starts the adapter, that does not even added to iobroker.

### CODE REVIEW

**Comment by foxriver76** [comment]
Do we really want to support this?

should already terminate here https://github.com/ioBroker/ioBroker.js-controller/blob/af352c4ad939adf20d6ec31187124d4314fb7c4c/packages/adapter/src/lib/adapter/adapter.ts#L844 why this does not happen there?

**Comment by GermanBluefox** [comment]
> Do we really want to support this?
> 
> should already terminate here
> 
> https://github.com/ioBroker/ioBroker.js-controller/blob/af352c4ad939adf20d6ec31187124d4314fb7c4c/packages/adapter/src/lib/adapter/adapter.ts#L844
> 
> why this does not happen there?

I have no Idea. But with the latest version I have this:
image

**Comment by foxriver76** [comment]
the root problem is that adapter dir is not found in such a scenario, so would ne to plug in their. However it should basically exit then - else the question for me is if we really need to support this scenario, we have a few better ways to debug a adapter nowadays.

**Comment by GermanBluefox** [comment]
So add at least `this.ioPack?.common?.plugins` to ignore the error

**Comment by foxriver76** [comment]
You can easily pass around it, by providing the actual `adapterDir` to the adapter constructor. Then we also don't have broken functionality in other places, because as stated in a productive scenario the adapter would have already been shut down. 

Else, we can implement some special logic to set the adapter dir, just like the host name for dev purposes like https://github.com/ioBroker/ioBroker.js-controller/blob/ff6975303d61f04653686fcde3284baab3f62485/packages/common/src/lib/common/tools.ts#L1574C1-L1576C6

**Comment by GermanBluefox** [comment]
> You can easily pass around it, by providing the actual `adapterDir` to the adapter constructor.

By every adapter I develop? 100 or so? It is immposible

**Comment by GermanBluefox** [comment]
We are discussing here about 2 question marks, that will save me tons of hours. Isn't that absurd?

**Comment by foxriver76** [comment]
> We are discussing here about 2 question marks, that will save me tons of hours. Isn't that absurd?

As soon as I understand how exactly you debug to even get this running, we will find a way, no problem with adding the question mark, even if I think there are more straight forward ways to debug. And currently I am not sure and cannot assess if it will save you tons of hours or will end up in a need for other workarounds later on to get the setup of one dev running. 

I now tried two scenarios to reproduce (Adapter not added to ioBroker as stated by you in the initial post): 

One started the adapter from workspace one from node modules but still not added to ioBroker, as expected, both fail. So how can I reproduce it?

image

**Comment by GermanBluefox** [comment]
scenarios to reproduce:
js-controller folder: `c:/pWork/node_modules/iobroker.js-controller`
hm-rega folder: `c:/pWork/iobroker.hm-rega`
By start of `cd c:/pWork/iobroker.hm-rega && node main.js --debug` I got
image

**Comment by foxriver76** [comment]
ah so its more about controller debugging and not adapter debugging of course then we have no dev-server yet. I think in general like in `main.ts` we should not crash just because we could not initalize plugins, so added try/catch around it. 

maybe someday with https://github.com/ioBroker/ioBroker.js-controller/pull/2161

**Review by foxriver76 — APPROVED** [review]

**Pull request merged**
