### PR TITLE
Add additional attribute (defAck) to object type state

### PR DESCRIPTION
**Pull request by Steiger04**
The documentation should be completed at https://github.com/ioBroker/ioBroker/blob/master/doc/SCHEMA.md#state-commonrole.
E.g.: common.defAck (optional) - If true - no acknowledgment for the value at instance creation.

### CODE REVIEW

**Comment by Steiger04** [comment]
@Apollon77 There seems to be a problem with travis. Any idea?

**Comment by Apollon77** [comment]
Yes, an earlier commit in 1.6.0-dev broke it by logging too much, so we need to ignore this here :-(
good to see that appveyor is green, so it should work basically :-) that's why i waited

**Comment by Apollon77** [comment]
Docs changed too: https://github.com/ioBroker/ioBroker/commit/cb2ec314e8837a8ee6724037c68c55d0c1e47b2e

**Comment by GermanBluefox** [comment]
Docu in iobroker.iobroker => schema

**Comment by Apollon77** [comment]
done, seel last comment. or do you mean somehwre different?

**Comment by GermanBluefox** [comment]
>done, seel last comment. or do you mean somehwre different?

Yes. Done.

**Pull request merged**
