### PR TITLE
Migrate to release-script v3

### PR DESCRIPTION
**Pull request by AlCalzone**
Now that release-script v3 is out, we should migrate to it. Notable changes:
* No more juggling with version/prerelease scripts, the release-script handles that now
* No manual removing the prerelase identifier in io-package.json, the release-script handles that now

Two things I'm not sure about:
1. I removed `lerna bootstrap` from the `prerelease` command. Is that necessary? The script automatically syncs package.json with package-lock.json before committing. If we need it, we can add it back by adding
```json
"exec": {
  "before_edit": "lerna bootstrap"
}
```
to .releaseconfig.json

2. ~~How do our crazy prerelease versions get into the files in the repo? I thought they were only used for nightlies. I would only keep the "normal" part `-alpha.8` in the files. That way we can make manual releases that correctly increment the postfix `-alpha.9`, `-alpha.10` etc. The "crazy" versions are chosen in a way that they are automatically lower than the "official" prereleases.~~
Also, wouldn't it be okay to have the short prerelease versions in `io-package.json`? That way we'd have more info from users to go off than `4.0.0` (_"...yeah 4.0.0, but which one?"_)

### CODE REVIEW

**Comment by foxriver76** [comment]
>    Also, wouldn't it be okay to have the short prerelease versions in `io-package.json`? That way we'd have more info from users to go off than `4.0.0` (_"...yeah 4.0.0, but which one?"_)

I think Ingo wanted to keep the workflow, so prereleases are pretty much for the nightly dev builds and not for end user installations. However, looking at npm we had prereleases once on latest tag for 3.2.6. So from my side, put it into io-pack too, it won't hurt - hopefully, not sure what admin etc is doing with that version ;-)

**Comment by AlCalzone** [comment]
> not sure what admin etc is doing with that version

AFAIK the only problem was that we used to have an outdated semver version which didn't compare prereleases properly. That should be fixed by now.

**Comment by Apollon77** [comment]
@AlCalzone Can oyu please rebase and maybe uodate deps to latest release script too? Thank you

**Comment by AlCalzone** [comment]
Will do tonight if I don't forget

**Pull request merged**
