### PR TITLE
Change validation scope within setBinaryState

### PR DESCRIPTION
**Pull request by theimo1221**
This might be a fix for #1425

### CODE REVIEW

**Comment by foxriver76** [comment]
But `setBinaryState` expects a foreign id, so why validate a own ns id..

permissionErrors are also not generated by `checkId`

**Comment by Apollon77** [comment]
@foxriver76 But then it is inconsistent ... setState makes local stuff setForeignState sets other stuff ... but setBinaryState only does Foreign cases ... hm ... so we need to docume t it and/or maybe allow setBinaryState to also work with "local" ids?

**Comment by theimo1221** [comment]
@Apollon77 We might better continue this discussion in #1425

**Comment by foxriver76** [comment]
> or maybe allow setBinaryState to also work with "local" ids?

Think of mqtt which often has namespaces off other adapters as substructures, it seems to be impossible to distinguish

**Pull request closed without merging**
