### PR TITLE
Corrected debug case for adapters

### PR DESCRIPTION
**Pull request by GermanBluefox**
`../../` leads from `.\node_modules\@iobroker\js-controller-common\build\lib\common` to `.\node_modules\@iobroker\js-controller-common\build\iobroker.web\package.json`

Earlier it was from `./node_modules/iobroker.js-controller/lib` and worked

`/../../../../../` leads from "./node_modules/@iobroker/js-controller-common/build/lib/common" to  `./node_modules/iobroker.web/package.json`  becasue of multi-packages and Typescript

The second check with `/../../../../../../` is required for "DEVELOPMENT"

### CODE REVIEW

**Comment by Apollon77** [comment]
@GermanBluefox Where and in which case  this is an issue?

**Comment by GermanBluefox** [comment]
> @GermanBluefox Where and in which case this is an issue?

I had a problem when during debugging, some packages were installed in `iobroker.js-controller/node_modules` folder. 
Earlier, we tried first to find the packages (e.g. admin) outside of js-controller. Now it does not work, because of the Typescript the location of `lib/tools.js` changed from

`./node_modules/iobroker.js-controller/lib`

to

`.\node_modules\@iobroker\js-controller-common\build\lib\common`

and `../..` does work anymore and we need `/../../../../../` (5 times)
Additionally, I tried to find the directory outside of `node_modules` (for this case `/../../../../../../` - 6 times) and it works

**Comment by foxriver76** [comment]
@GermanBluefox can youn try if this change also works in your scenarios? 

https://github.com/ioBroker/ioBroker.js-controller/pull/2363/files

It would be robust to future refactoring + more readable

**Comment by foxriver76** [comment]
Should work with GitHub Version

**Pull request closed without merging**
