### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by paul53**
cpu usage in % of one core: common.type 'number' --> 'string'

### CODE REVIEW

**Comment by Apollon77** [comment]
Why? It is a number in %

**Comment by paul53** [comment]
It's a string. See line 633: .toFixed(2)

**Comment by AlCalzone** [comment]
Uhm I'd much fix the line 633 then. This should be a number, we just need to round it properly.

**Comment by Apollon77** [comment]
Then we should better fix that and write the number so a parseFloat of the  toFixed

**Comment by AlCalzone** [comment]
> Then we should better fix that and write the number so a parseFloat of the toFixed

No, not number -> string -> number...
`Math.round(num * 100) / 100`

**Comment by Apollon77** [comment]
Ist ja ok ;-)) waee tree um close?

**Comment by AlCalzone** [comment]
Sprichst du jetzt finnisch?

**Comment by Apollon77** [comment]
lol ... wtf handy ...

**Pull request closed without merging**
