### PR TITLE
Issue/2098/certificate collections

### PR DESCRIPTION
**Pull request by raintonr**
I'm sure there's plenty here someone won't like. Review away...

### CODE REVIEW

**Comment by Apollon77** [comment]
We will add this into js-controller 5.

I just would question if we shoukd stay with "we expose such stuff like the webserver via js-controller" and not create an own mini @ipbropker/sslwebserver npm package. We could still "expose" it via adapter-core or simply not :-)

**Comment by raintonr** [comment]
> We will add this into js-controller 5.
> 
> I just would question if we shoukd stay with "we expose such stuff like the webserver via js-controller" and not create an own mini @ipbropker/sslwebserver npm package.

I'm all for moving as much code as possible into another package as js-controller is way too large as it is.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/webserver

will be reviewed by @Apollon77, then we decide how to proceed

**Comment by Apollon77** [comment]
@foxriver76 Comments:
* GitHub actions missing :-)
* https://github.com/ioBroker/webserver/blob/c9b52f332105235ffc29444fcb732d9efc969bd3/src/lib/certificateManager.ts#L35-L36 ... i would make two deparate methods getAllCollections amd getCollection(id) kind of
* https://github.com/ioBroker/webserver/blob/main/src/lib/certificateManager.ts#L146 ... would call get getCollectionIds (so not "List")
* maybe return the server? https://github.com/ioBroker/webserver/blob/main/src/lib/webserver.ts#L30 ... more straight forward usage

**Comment by foxriver76** [comment]
> @foxriver76 Comments:
> 
>     * GitHub actions missing :-)

The repo currently has no tests, and as it is adapter dependent, I am not sure if it makes sense to add tests from a cost/usefulness perspective. Hence, I don't really see CI tests there for now. We could add release script with publish workflow though. 

>     * https://github.com/ioBroker/webserver/blob/c9b52f332105235ffc29444fcb732d9efc969bd3/src/lib/certificateManager.ts#L35-L36 ... i would make two deparate methods getAllCollections amd getCollection(id) kind of

also thought about this, instead of the overloads. we can do.

>     * https://github.com/ioBroker/webserver/blob/main/src/lib/certificateManager.ts#L146 ... would call get getCollectionIds (so not "List")

:+1:

>     * maybe return the server? https://github.com/ioBroker/webserver/blob/main/src/lib/webserver.ts#L30 ... more straight forward usage

:+1:

**Comment by raintonr** [comment]
Please don't forget that the ACME adapter requires access to get/set collections stuff: https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js

**Comment by foxriver76** [comment]
> Please don't forget that the ACME adapter requires access to get/set collections stuff: https://github.com/iobroker-community-adapters/ioBroker.acme/blob/main/main.js

Yes this stuff is exported as CertificationManager by the module.

**Comment by raintonr** [comment]
> Yes this stuff is exported as CertificationManager by the module.

Shouldn't CertificationManager be self contained then and used by both webserver and ACME (and the self-signed generator + any other future options)? Sorry :disappointed:

**Comment by foxriver76** [comment]
> > Yes this stuff is exported as CertificationManager by the module.
> 
> Shouldn't CertificationManager be self contained then and used by both webserver and ACME (and the self-signed generator + any other future options)? Sorry disappointed

it is currently a whole separate file, I don't see the need for splitting it up in another module yet. Wouldn't be a problem at any time. I am not deep in the topic as I am not using all this stuff.

**Comment by foxriver76** [comment]
> @foxriver76 Comments:
> 
>     * GitHub actions missing :-)
> 
>     * https://github.com/ioBroker/webserver/blob/c9b52f332105235ffc29444fcb732d9efc969bd3/src/lib/certificateManager.ts#L35-L36 ... i would make two deparate methods getAllCollections amd getCollection(id) kind of
> 
>     * https://github.com/ioBroker/webserver/blob/main/src/lib/certificateManager.ts#L146 ... would call get getCollectionIds (so not "List")
> 
>     * maybe return the server? https://github.com/ioBroker/webserver/blob/main/src/lib/webserver.ts#L30 ... more straight forward usage

ready for re-review

**Comment by Apollon77** [comment]
Approved :-)

**Pull request closed without merging**
