### PR TITLE
Aliases

### PR DESCRIPTION
**Pull request by GermanBluefox**
This is first approach of aliases. And it works. Looks not too complex, but the admin will be complex

### CODE REVIEW

**Comment by Apollon77** [comment]
Cool. I will check it after vacation...

**Comment by Apollon77** [comment]
Very short check and comments:
We use Singular in most cases eg „enum“ so e should also get go with „alias“ instead of „aliases“. 

Rest i need to check deeper after vacation. Why you added all those null parameters?

**Comment by GermanBluefox** [comment]
> Rest i need to check deeper after vacation. Why you added all those null parameters?

Because my WebStorm showed it. :)
I will rename into "alias"

**Comment by Apollon77** [comment]
Do you want to create an admin issue with your plan for it?

**Pull request merged**
